# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/

APPLY_FIXES: none

ENABLE_LINTERS:
  - JSON_JSONLINT
  - BASH_SHELLCHECK
  - MARKDOWN_MARKDOWNLINT

SHOW_ELAPSED_TIME: true
